#ifndef __IO_DEFINE_H__
#define __IO_DEFINE_H__ 

#include "NUC123.h"

#define GPIO_PA               	   	0UL
#define GPIO_PB               	   	1UL
#define GPIO_PC               	   	2UL
#define GPIO_PD               	   	3UL
#define GPIO_PE               	   	4UL	//has not PE
#define GPIO_PF               	   	5UL

#define GPIO_SET_MODE(port, pin, mode) *((volatile uint32_t *)(GPIO_BASE + (port << 6))) = (*((volatile uint32_t *)(GPIO_BASE + (port << 6))) & ~(0x3 << (pin << 1))) | (mode << (pin << 1))

//PVSS 		  				p1

#define GPIO_MIC_MUTE				GPIO_PB	// p2
#define GPIO_MIC_MUTE_PIN			8
#define GPIO_MIC_MUTE_PO(x)       	GPIO_PIN_DATA(GPIO_MIC_MUTE, GPIO_MIC_MUTE_PIN) = x
#define GPIO_MIC_MUTE_INIT()      	GPIO_SET_MODE(GPIO_MIC_MUTE, GPIO_MIC_MUTE_PIN, GPIO_PMD_OUTPUT)
#define GPIO_MIC_MUTE_SET_MUTE()	GPIO_MIC_MUTE_PO(1)
#define GPIO_MIC_MUTE_SET_RELEASE()	GPIO_MIC_MUTE_PO(0)

#define GPIO_E_DET					GPIO_PB	// p3
#define GPIO_E_DET_PIN				14
#define GPIO_E_DET_PI()	       		GPIO_PIN_DATA(GPIO_E_DET, GPIO_E_DET_PIN)
#define GPIO_E_DET_INIT()      		GPIO_SET_MODE(GPIO_E_DET, GPIO_E_DET_PIN, GPIO_PMD_INPUT)
#define GPIO_E_DET_IN				1
#define GPIO_E_DET_OUT				0

#define GPIO_WM8974_SCL				GPIO_PA	// p4
#define GPIO_WM8974_SCL_PIN			11
#define GPIO_WM8974_SCL_PO(x)       GPIO_PIN_DATA(GPIO_WM8974_SCL, GPIO_WM8974_SCL_PIN) = x
#define GPIO_WM8974_SCL_OUT()       GPIO_SET_MODE(GPIO_WM8974_SCL, GPIO_WM8974_SCL_PIN, GPIO_PMD_QUASI)
#define GPIO_WM8974_SCL_INIT()      GPIO_SET_MODE(GPIO_WM8974_SCL, GPIO_WM8974_SCL_PIN, GPIO_PMD_QUASI)

#define GPIO_WM8974_SDA				GPIO_PA	// p5
#define GPIO_WM8974_SDA_PIN			10
#define GPIO_WM8974_SDA_PO(x)       GPIO_PIN_DATA(GPIO_WM8974_SDA, GPIO_WM8974_SDA_PIN) = x
#define GPIO_WM8974_SDA_PI()        GPIO_PIN_DATA(GPIO_WM8974_SDA, GPIO_WM8974_SDA_PIN)
#define GPIO_WM8974_SDA_IN()    	GPIO_SET_MODE(GPIO_WM8974_SDA, GPIO_WM8974_SDA_PIN, GPIO_PMD_QUASI)
#define GPIO_WM8974_SDA_OUT()       GPIO_SET_MODE(GPIO_WM8974_SDA, GPIO_WM8974_SDA_PIN, GPIO_PMD_QUASI)
#define GPIO_WM8974_SDA_INIT()      GPIO_SET_MODE(GPIO_WM8974_SDA, GPIO_WM8974_SDA_PIN, GPIO_PMD_QUASI)

//RXD1 				PB4		p6
//TXD1 				PB5		p7

#define GPIO_MIC_LED_G				GPIO_PB	// p8
#define GPIO_MIC_LED_G_PIN			6
#define GPIO_MIC_LED_G_PO(x)       	GPIO_PIN_DATA(GPIO_MIC_LED_G, GPIO_MIC_LED_G_PIN) = x
#define GPIO_MIC_LED_G_INIT()      	GPIO_SET_MODE(GPIO_MIC_LED_G, GPIO_MIC_LED_G_PIN, GPIO_PMD_QUASI)
#define GPIO_MIC_LED_G_ON()			GPIO_MIC_LED_G_PO(0)
#define GPIO_MIC_LED_G_OFF()		GPIO_MIC_LED_G_PO(1)

#define GPIO_MIC_LED_R				GPIO_PB	// p9
#define GPIO_MIC_LED_R_PIN			7
#define GPIO_MIC_LED_R_PI()			GPIO_PIN_DATA(GPIO_MIC_LED_R, GPIO_MIC_LED_R_PIN)
#define GPIO_MIC_LED_R_PO(x)       	GPIO_PIN_DATA(GPIO_MIC_LED_R, GPIO_MIC_LED_R_PIN) = x
#define GPIO_MIC_LED_R_INIT()      	GPIO_SET_MODE(GPIO_MIC_LED_R, GPIO_MIC_LED_R_PIN, GPIO_PMD_QUASI)
#define GPIO_MIC_LED_R_ON()			GPIO_MIC_LED_R_PO(0)
#define GPIO_MIC_LED_R_OFF()		GPIO_MIC_LED_R_PO(1)


//LDO  						P10
//VDD  						P11
//GND  						P12
//VBUS 						P13
//VDD33						P14
//DM0						P15
//DP0						P16
//TXD0				PC5		P17
//RXD0				PC4		P18

#define GPIO_POWER_SW				GPIO_PC	// P19
#define GPIO_POWER_SW_PIN			3
#define GPIO_POWER_SW_PI()	       	GPIO_PIN_DATA(GPIO_POWER_SW, GPIO_POWER_SW_PIN)
#define GPIO_POWER_SW_INIT()      	GPIO_SET_MODE(GPIO_POWER_SW, GPIO_POWER_SW_PIN, GPIO_PMD_INPUT)

#define GPIO_POWER_CTL				GPIO_PC	// P20
#define GPIO_POWER_CTL_PIN			2
#define GPIO_POWER_CTL_PO(x)       	GPIO_PIN_DATA(GPIO_POWER_CTL, GPIO_POWER_CTL_PIN) = x
#define GPIO_POWER_CTL_INIT()      	GPIO_SET_MODE(GPIO_POWER_CTL, GPIO_POWER_CTL_PIN, GPIO_PMD_OUTPUT)
#define GPIO_POWER_CTL_ON()			GPIO_POWER_CTL_PO(1)
#define GPIO_POWER_CTL_OFF()		GPIO_POWER_CTL_PO(0)

#define GPIO_AU_MUTE				GPIO_PC	// P21
#define GPIO_AU_MUTE_PIN			1
#define GPIO_AU_MUTE_PO(x)	       	GPIO_PIN_DATA(GPIO_AU_MUTE, GPIO_AU_MUTE_PIN) = x
#define GPIO_AU_MUTE_INIT()      	GPIO_SET_MODE(GPIO_AU_MUTE, GPIO_AU_MUTE_PIN, GPIO_PMD_OUTPUT)
#define GPIO_AU_MUTE_SET_MUTE()		GPIO_AU_MUTE_PO(0)
#define GPIO_AU_MUTE_SET_RELEASE()	GPIO_AU_MUTE_PO(1)

#define GPIO_OLED_POWER_CTL			GPIO_PC	// P22
#define GPIO_OLED_POWER_CTL_PIN		0
#define GPIO_OLED_POWER_CTL_PO(x)   GPIO_PIN_DATA(GPIO_OLED_POWER_CTL, GPIO_OLED_POWER_CTL_PIN) = x
#define GPIO_OLED_POWER_CTL_INIT()  GPIO_SET_MODE(GPIO_OLED_POWER_CTL, GPIO_OLED_POWER_CTL_PIN, GPIO_PMD_OUTPUT)
#define GPIO_OLED_POWER_CTL_ON()	GPIO_OLED_POWER_CTL_PO(1)
#define GPIO_OLED_POWER_CTL_OFF()	GPIO_OLED_POWER_CTL_PO(0)

#define GPIO_OLED_VBAT				GPIO_PB	// P23
#define GPIO_OLED_VBAT_PIN			10
#define GPIO_OLED_VBAT_PO(x)       	GPIO_PIN_DATA(GPIO_OLED_VBAT, GPIO_OLED_VBAT_PIN) = x
#define GPIO_OLED_VBAT_INIT()      	GPIO_SET_MODE(GPIO_OLED_VBAT, GPIO_OLED_VBAT_PIN, GPIO_PMD_OUTPUT)

//NIC				PB9	    P24

#define GPIO_OLED_DC				GPIO_PC	// P25
#define GPIO_OLED_DC_PIN			13
#define GPIO_OLED_DC_PO(x)       	GPIO_PIN_DATA(GPIO_OLED_DC, GPIO_OLED_DC_PIN) = x
#define GPIO_OLED_DC_INIT()      	GPIO_SET_MODE(GPIO_OLED_DC, GPIO_OLED_DC_PIN, GPIO_PMD_OUTPUT)

#define GPIO_OLED_RST				GPIO_PC	// P26
#define GPIO_OLED_RST_PIN			12
#define GPIO_OLED_RST_PO(x)       	GPIO_PIN_DATA(GPIO_OLED_RST, GPIO_OLED_RST_PIN) = x
#define GPIO_OLED_RST_INIT()      	GPIO_SET_MODE(GPIO_OLED_RST, GPIO_OLED_RST_PIN, GPIO_PMD_OUTPUT)

//OLED_MOSI			PC11    P27
//NIC				PC10	P28
//OLED_CLK			PC9		P29
//OLED_CS			PC8		P30
//SRJ02				PA15	P31
//SRJ01				PA14	P32

#define GPIO_MASTER_CHOOSE		    GPIO_PA	// P32
#define GPIO_MASTER_CHOOSE_PIN		14
#define GPIO_MASTER_CHOOSE_PI()	    GPIO_PIN_DATA(GPIO_MASTER_CHOOSE, GPIO_MASTER_CHOOSE_PIN)
#define GPIO_MASTER_CHOOSE_INIT()   GPIO_SET_MODE(GPIO_MASTER_CHOOSE, GPIO_MASTER_CHOOSE_PIN, GPIO_PMD_QUASI)

#define GPIO_CHARGE_CHECK			GPIO_PA	// P33
#define GPIO_CHARGE_CHECK_PIN		13
#define GPIO_CHARGE_CHECK_PI()	    GPIO_PIN_DATA(GPIO_CHARGE_CHECK, GPIO_CHARGE_CHECK_PIN)
#define GPIO_CHARGE_CHECK_INIT()    GPIO_SET_MODE(GPIO_CHARGE_CHECK, GPIO_CHARGE_CHECK_PIN, GPIO_PMD_INPUT)

//NIC				PA12	P34
//ICE_DAT					P35
//ICE_CLK					P36
//AVDD						P37
//VBAT_CHECK		PD0		P38
//MIC1_WAKE_OUT		PD1		P39

#define GPIO_KEY_VIP				GPIO_PD	// P40
#define GPIO_KEY_VIP_PIN			2
#define GPIO_KEY_VIP_PI()	       	GPIO_PIN_DATA(GPIO_KEY_VIP, GPIO_KEY_VIP_PIN)
#define GPIO_KEY_VIP_INIT()      	GPIO_SET_MODE(GPIO_KEY_VIP, GPIO_KEY_VIP_PIN, GPIO_PMD_INPUT)

#define GPIO_KEY_MIC_KEY			GPIO_PD	// P41
#define GPIO_KEY_MIC_KEY_PIN		3
#define GPIO_KEY_MIC_KEY_PI()	    GPIO_PIN_DATA(GPIO_KEY_MIC_KEY, GPIO_KEY_MIC_KEY_PIN)
#define GPIO_KEY_MIC_KEY_INIT()     GPIO_SET_MODE(GPIO_KEY_MIC_KEY, GPIO_KEY_MIC_KEY_PIN, GPIO_PMD_INPUT)

//MICBASE			PD4		P42
//CHARING_CHECK		PD5		P43
//NIC				PF0		P44
//NIC				PF1		P45
//RESET						P46

#define GPIO_DISPLAY_VIP			GPIO_PF	// P47
#define GPIO_DISPLAY_VIP_PIN		2
#define GPIO_DISPLAY_VIP_PO(x)  	GPIO_PIN_DATA(GPIO_DISPLAY_VIP, GPIO_DISPLAY_VIP_PIN) = x
#define GPIO_DISPLAY_VIP_INIT() 	GPIO_SET_MODE(GPIO_DISPLAY_VIP, GPIO_DISPLAY_VIP_PIN, GPIO_PMD_QUASI)
#define GPIO_DISPLAY_VIP_ON()		GPIO_DISPLAY_VIP_PO(0)
#define GPIO_DISPLAY_VIP_OFF()		GPIO_DISPLAY_VIP_PO(1)

#define GPIO_DISPLAY_MIC			GPIO_PF	// P48
#define GPIO_DISPLAY_MIC_PIN		3
#define GPIO_DISPLAY_MIC_PI()	    GPIO_PIN_DATA(GPIO_DISPLAY_MIC, GPIO_DISPLAY_MIC_PIN)
#define GPIO_DISPLAY_MIC_PO(x)  	GPIO_PIN_DATA(GPIO_DISPLAY_MIC, GPIO_DISPLAY_MIC_PIN) = x
#define GPIO_DISPLAY_MIC_INIT() 	GPIO_SET_MODE(GPIO_DISPLAY_MIC, GPIO_DISPLAY_MIC_PIN, GPIO_PMD_QUASI)
#define GPIO_DISPLAY_MIC_ON()			GPIO_DISPLAY_MIC_PO(0)
#define GPIO_DISPLAY_MIC_OFF()		GPIO_DISPLAY_MIC_PO(1)


#endif

